---
  version: 1
  schedule: 
    type: "simple"
    interval: "10s"
  max-failures: 10
  workflow: 
    collect: 
      metrics: 
        /staples/couchbase/*: {}
      config: 
      process: 
        - 
          plugin_name: "passthru"
          process: null
          publish: 
            - 
              plugin_name: "mock-file"
              config: 
                file: "./snap_published_couchbase_file.log"

